version: '3.8'
services:
  bookmarker-api:
    build:
      context: bookmarker-api
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://bookmarker-db:5432/appdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "18585:8585"
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - bookmarker-network

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bookmarker-network

  bookmarker-ui-nextjs:
    container_name: bookmarker-ui-nextjs
    build: 
      context: bookmarker-ui-nextjs
      dockerfile: Dockerfile.ui
    ports:
      - "13000:3000"
    env_file: 
      - ./bookmarker-ui-nextjs/.env.local
    networks:
      - bookmarker-network

networks:
  bookmarker-network:
    driver: bridge
