# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Build

on:
  push:
    branches: ["**"]

jobs:
  build-bookmark-api:
    name: Build bookmarker-api
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bookmarker-api
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      # Maven build 작업시 권한으로 인한 접근 허용 
      - name: Build with Maven
        run: |
          chmod +x mvnw 
          ./mvnw verify

      # docker의 tty 명령어를 사용하기 위한 환경설정 및 Docker 이미지 빌드/배포
      - name: Build and Publish Docker Image
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          ./mvnw clean package jib:dockerBuild -DskipTests
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t myimage:latest .
          docker tag myimage:latest ${{ secrets.DOCKER_USERNAME }}/bookmarker-api:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/bookmarker-api:latest
        env: 
          DOCKER_BUILDKIT: 1
          DOCKER_CLI_EXPERIMENTAL: enabled

  build-bookmarker-ui:
    name: Build bookmarker-ui
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bookmarker-ui-nextjs
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 20.9.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0
          cache: 'yarn'
          cache-dependency-path: bookmarker-ui-nextjs/yarn.lock

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Build and Publish Docker Image
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker build -f Dockerfile.ui -t ${{ secrets.DOCKER_USERNAME }}/bookmarker-ui-nextjs .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/bookmarker-ui-nextjs
